language: generic
sudo: false

cache:
  directories:
    - $HOME/opt

matrix:
  include:
    - os: linux
      env: VIM=vim OPT=$HOME/opt VIMPROG=$OPT/bin/$VIM
    - os: linux
      env: VIM=nvim VIMPROG=$VIM
    - os: osx
      env: VIM=vim PACKAGE=vim VIMPROG=$VIM
    - os: osx
      env: VIM=nvim PACKAGE=neovim VIMPROG=$VIM


install: |
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    if [ "$VIM" = "vim" ]; then
      git clone --depth 1 https://github.com/vim/vim
      cd vim
      echo -n 'Vim version: '
      git describe --tags | tee vim-ver.txt
      if [ -e $OPT/vim-ver.txt ]; then
        if diff $OPT/vim-ver.txt vim-ver.txt; then
          cd -
          return
        fi
      fi
      ./configure --prefix=$OPT --with-features=huge --disable-gui
      make
      make install
      cp vim-ver.txt $OPT
      cd -
    elif [ "$VIM" = "nvim" ]; then
      # https://github.com/neovim/bot-ci#setting-up-integration-builds
      eval "$(curl -Ss https://raw.githubusercontent.com/neovim/bot-ci/master/scripts/travis-setup.sh) nightly-x64"
    fi
  elif [ "$TRAVIS_OS_NAME" = "osx" ]; then
    if [ -d $HOME/opt/cache ]; then
      cp $HOME/opt/cache/* $HOME/Library/Caches/Homebrew
    else
      mkdir $HOME/opt/cache -p
    fi
    (cd $HOME/Library/Caches/Homebrew; ls > $HOME/list1.txt)
    brew update
    #brew upgrade
    brew install $PACKAGE
    brew cleanup -s
    (cd $HOME/Library/Caches/Homebrew; ls > $HOME/list2.txt)
    comm -2 -3 $HOME/list1.txt $HOME/list2.txt | (cd $HOME/Library/Caches/Homebrew; xargs -I{} cp {} $HOME/opt/cache)
    comm -1 -3 $HOME/list1.txt $HOME/list2.txt | (cd $HOME/opt/cache/; xargs rm -rf)
    $VIM --version
  fi

script:
  - cd test
  - make VIMPROG=$VIMPROG

# vim: sw=2 sts=2 et
