version: '1.0.{build}'

shallow_clone: true

environment:
  AUTH_TOKEN: # for GitHub
    secure: wdTzzL05DoG4BZIgqlc3y/Ff50ZOTjfaqMazhdMLcXmxYYbmeCsI9PN01TJCQMaw
  API_TOKEN:  # for AppVeyor
    secure: iUTvK78Ch5hfdoqFtPOMeQj96cGeeyenSfCRJxLb650=

build_script:
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'
  - tools\appveyor-dl.bat

test_script:
  - cd test
  - nmake -f Make_win.mak VIMPROG=%APPVEYOR_BUILD_FOLDER%\vim80-kaoriya-win64\gvim.exe

cache:
  - downloads -> appveyor.yml

# vim: sw=2 sts=2 et
